# Generated by Django 4.2 on 2023-04-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.student'),
        ),
    ]
