# Generated by Django 4.2 on 2023-04-17 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useraccount.teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useraccount.student'),
        ),
    ]
